force-app/main/default/objects/Patients__c/Patients__c.object-meta.xml
<CustomObject>
    <label>Patients</label>
    <nameField>
        <label>Patients ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Patients__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last_Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patients__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admitted</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
            <value>
                <fullName>In treatement</fullName>
            </value>
            <value>
                <fullName>outpatient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PatientController.cls
public with sharing class PatientController {
    @AuraEnabled
    public static List<Patients__c> searchPatients(String searchKey) {
        // Return matching patients based on First Name
        if(String.isBlank(searchKey)) {
            return new List<Patients__c>();
        }
        return [
            SELECT Id, First_Name__c, Last_Name__c, Status__c
            FROM Patients__c
            WHERE First_Name__c LIKE :('%' + searchKey + '%')
            ORDER BY First_Name__c ASC
        ];
    }
}